Repository matsuo-group24-PinkTrombone/SpeechGeneration, pull requests merged in 2023-01, with the labels that each got.

#6 このリポジトリのテンプレートとなるコード階層を記述しました.
  .github/ISSUE_TEMPLATE/タスク追加.md
  .github/ISSUE_TEMPLATE/不具合報告.md
  .github/ISSUE_TEMPLATE/機能要望.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .pre-commit-config.yaml
  AboutProject.md
  Makefile
  README.md
  configs/README.md
  data/README.md
  logs/.gitkeep
  pyproject.toml
  scripts/README.md
  src/README.md
  src/__init__.py
  src/datamodules/__init__.py
  src/datamodules/components/__init__.py
  src/models/__init__.py
  src/models/abc/__init__.py
  src/models/components/__init__.py
  src/test.py
  src/train.py
  src/utils/__init__.py
  tests/README.md
  tests/__init__.py
  tests/datamodules/__init__.py
  tests/models/__init__.py
  tests/utils/__init__.py
Labels: enhancement

#10 Pythonの依存関係を追加
  pyproject.toml
Labels: enhancement

#11 環境構築の方法を整備しました。
  AboutProject.md
  Dockerfile
  Makefile
  SetupProject.md
  scripts/docker-entrypoint.sh
  scripts/setup-on-aws.sh
Labels: enhancement

#14 Conditional VAEのPostorierEncoderを追加する
  pyproject.toml
  src/models/components/posterior_encoder_vits.py
  src/models/components/wavenet/__init__.py
  src/models/components/wavenet/residual_block.py
  src/models/components/wavenet/wavenet.py
  src/utils/nets_utils.py
  tests/helpers/__init__.py
  tests/helpers/feats_extract/__init__.py
  tests/helpers/feats_extract/abs_feats_extract.py
  tests/helpers/feats_extract/log_mel_fbank.py
  tests/helpers/feats_extract/test_log_mel_fbank.py
  tests/helpers/layers/__init__.py
  tests/helpers/layers/complex_utils.py
  tests/helpers/layers/inversible_interface.py
  tests/helpers/layers/log_mel.py
  tests/helpers/layers/stft.py
  tests/helpers/layers/test_complex_utils.py
  tests/helpers/layers/test_log_mel.py
  tests/helpers/layers/test_stft.py
  tests/models/components/test_posterior_encoder_vits.py
  tests/models/components/wavenet/test_residual_block.py
  tests/models/components/wavenet/test_wavenet.py
  tests/utils/test_nets_utils.py
Labels: enhancement

#23 コンポーネントモデルの抽象クラス作成
  src/models/abc/_types.py
  src/models/abc/controller.py
  src/models/abc/observation_auto_encoder.py
  src/models/abc/prior.py
  src/models/abc/transition.py
  tests/models/abc/__init__.py
  tests/models/abc/test_controller.py
  tests/models/abc/test_observation_auto_encoder.py
  tests/models/abc/test_prior.py
  tests/models/abc/test_transition.py
Labels: enhancement

#24 Controllerモデルの戻り値を修正（next controller hiddenを追加)
  src/models/abc/controller.py
  tests/models/abc/test_controller.py
Labels: bug

#22 ReplayBufferの実装を追加
  Makefile
  src/datamodules/replay_buffer.py
  tests/datamodules/test_replay_buffer.py
Labels: documentation, enhancement

#26 ローカル環境上でのDockerによる開発環境の方法を整備しました。
  .devcontainer/devcontainer.json
  Dockerfile
  Makefile
  SetupProject.md
  scripts/docker-entrypoint.sh
Labels: enhancement

#28 抽象Controllerモデルにabstract property `hidden_shape`を実装しました。
  src/models/abc/controller.py
  tests/models/abc/test_controller.py
Labels: enhancement

#30 Hydraのinstantiateのドキュメントを追加
  configs/README.md
Labels: documentation

#31 train.pyのエントリーポイントをhydraを用いて実装しました。
  .project-root
  configs/README.md
  configs/hydra/default.yaml
  configs/paths/default.yaml
  configs/train.yaml
  pyproject.toml
  src/train.py
Labels: enhancement

#29 Agent modelとWorld modelの抽象クラスを追加し、テスト用のダミー具象クラスを実装しました。
  src/models/abc/agent.py
  src/models/abc/world.py
  tests/models/abc/dummy_classes.py
  tests/models/abc/test_agent.py
  tests/models/abc/test_dummy_classes.py
  tests/models/abc/test_world.py
Labels: enhancement

#41 デバッグするためのターゲット音声ファイルを追加
  .gitignore
  data/README.md
  data/sample_target_sounds/epiglottis_0-3.5.wav
  data/sample_target_sounds/nothing.wav
  data/sample_target_sounds/tenseness_0-1.wav
  data/sample_target_sounds/trachea_0-3.5.wav
Labels: enhancement

#38 PriorEncoderの実装
  src/models/components/prior_encoder.py
  tests/models/components/test_prior_encoder.py
Labels: enhancement

#43 行動の値域を[-1,1]にするNormalizeActionRangeクラスを実装
  src/env/normalize_action_range.py
  tests/env/test_normalize_action_range.py
  tests/helpers/paths.py
Labels: enhancement

#44 辞書型の行動を配列型で扱えるようにするActionWrapperクラスを実装しました。
  src/env/array_action.py
  tests/env/test_array_action.py
Labels: enhancement

#45 観測の声道モデル`Voc`の状態情報を配列化する観測ラッパークラスを作成しました。
  src/env/array_voc_state.py
  tests/env/test_array_voc_state.py
Labels: enhancement

#39 TransitionModelの実装
  src/models/components/transition.py
  tests/models/components/test_transition.py
Labels: enhancement

#48 Feature/#21controller model
  src/models/components/controller.py
  src/models/components/posterior_encoder_vits.py
  tests/models/components/test_controller.py
Labels: enhancement

#50 タイポと条件の修正
  src/models/components/prior_encoder.py
  src/models/components/transition.py
  tests/models/components/test_prior_encoder.py
  tests/models/components/test_transition.py
Labels: bug

#27 Feature/#15conformer
  src/models/components/conformer/__init__.py
  src/models/components/conformer/attention.py
  src/models/components/conformer/convolution.py
  src/models/components/conformer/embedding.py
  src/models/components/conformer/encoder.py
  src/models/components/conformer/encoder_layer.py
  src/models/components/conformer/layer_norm.py
  src/models/components/conformer/multi_layer_conv.py
  src/models/components/conformer/postnet.py
  src/models/components/conformer/repeat.py
  src/models/components/conformer/swish.py
  src/models/components/conformer_decoder_fastspeech2.py
  src/utils/nets_utils.py
  tests/models/components/conformer/test_attention.py
  tests/models/components/conformer/test_convolution.py
  tests/models/components/conformer/test_embedding.py
  tests/models/components/conformer/test_encoder.py
  tests/models/components/conformer/test_encoder_layer.py
  tests/models/components/conformer/test_layer_norm.py
  tests/models/components/conformer/test_multi_layer_conv.py
  tests/models/components/conformer/test_postnet.py
  tests/models/components/conformer/test_repeat.py
  tests/models/components/conformer/test_swish.py
  tests/models/components/test_conformer_decoder_fastspeech2.py
Labels: enhancement

#59 環境作成関数make_envの実装
  src/env/make_env.py
  tests/env/test_make_env.py
Labels: enhancement

#65 Dreamerクラスにtensorboardによる記録処理を実装しました
  pyproject.toml
  src/models/dreamer.py
  tests/models/test_dreamer.py
Labels: enhancement
