Repository matsuo-group24-PinkTrombone/SpeechGeneration, pull requests merged in 2023-02, with the labels that each got.

#66 Dreamerのcontroller_training_stepを修正しました
  src/models/dreamer.py
Labels: bug

#69 Agentクラスを実装しました。
  src/models/components/agent.py
  tests/models/abc/dummy_classes.py
  tests/models/components/__init__.py
  tests/models/components/test_agent.py
Labels: enhancement

#63 Trainerクラスのテスト
  src/models/abc/agent.py
  src/models/components/controller.py
  src/models/dreamer.py
  src/trainer.py
  tests/models/abc/dummy_classes.py
  tests/models/abc/test_agent.py
  tests/models/test_dreamer.py
  tests/test_trainer.py
Labels: enhancement

#72 Configure replay buffer space
  src/models/dreamer.py
  tests/models/test_dreamer.py
  tests/test_trainer.py
Labels: enhancement

#75 ログをコンソールにアウトプット
  src/trainer.py
  tests/test_trainer.py
Labels: enhancement

#79 Hydraでinstantiateするためのconfigファイルとそのテストコードを作成しました。
  configs/env/make_env.yaml
  configs/model/dreamer.yaml
  configs/replay_buffer/replay_buffer.yaml
  configs/trainer/trainer.yaml
  src/models/components/world.py
  src/trainer.py
  tests/test_config_files/__init__.py
  tests/test_config_files/env/__init__.py
  tests/test_config_files/env/test_make_env.py
  tests/test_config_files/model/__init__.py
  tests/test_config_files/model/test_dreamer.py
  tests/test_config_files/replay_buffer/__init__.py
  tests/test_config_files/replay_buffer/test_replay_buffer.py
  tests/test_config_files/trainer/__init__.py
  tests/test_config_files/trainer/test_trainer.py
  tests/test_trainer.py
Labels: enhancement

#81 train関数を実装し、学習を開始しました。
  configs/model/dreamer.yaml
  configs/train.yaml
  configs/trainer/trainer.yaml
  src/models/dreamer.py
  src/train.py
  src/trainer.py
  src/utils/reset_seed.py
Labels: enhancement

#84 実験を放置するために`screen`パッケージを依存関係に追加しました。
  Dockerfile
Labels: enhancement

#90 ADD configuration `default_frequency`
  src/env/make_env.py
  tests/env/test_make_env.py
Labels: enhancement

#83 実験用のconfigファイルを作成し、上書きできる機能を追加しました。
  configs/experiment/example.yaml
  configs/train.yaml
Labels: enhancement

#93 agentの`hidden`と`controller_hidden`をproperty化
  src/models/abc/agent.py
Labels: fix bugs

#100 LogMelSpectrogramに変換する観測ラッパークラスを作成しました。
  src/env/log_mel_spectrogram.py
  tests/env/test_log_mel_spectrogram.py
Labels: enhancement

#96 show imagination horizon
  src/models/dreamer.py
  src/utils/visualize.py
  tests/utils/test_visualize.py
Labels: enhancement
